type = "card"
title = "Services & Activities"
description = "Professional services and community involvement."

[[items]]
title = "Reviewer"
subtitle = "Journal of Accounting, Auditing and Finance"
# date = "2026"
# content = "Reviewed papers for..."

[[items]]
title = "Discussant"
subtitle = "2026 AAA International Accounting Section Midyear Meeting, Cincinnati, OH"
# date = "2026"

[[items]]
title = "Moderator"
subtitle = "2026 AAA International Accounting Section Midyear Meeting, Cincinnati, OH"
# date = "2026"



[[items]]
title = "Participation"
subtitle = """2026 AAA FARS Midyear Meeting, San Antonio, TX
2026 AAA International Accounting Section Midyear Meeting, Cincinnati, OH
2026 Oklahoma State University Ph.D. Alumni Research Conference, Tulsa, OK
2025 Journal of Accounting, Auditing and Finance Symposium, New York, NY
2025 AAA FARS Midyear Meeting, Atlanta, GA
2024 University of Arizona / Arizona State University Joint Research Conference, Tempe, AZ
2023 University of Arizona / Arizona State University Joint Research Conference, Tucson, AZ"""